May 23rd: Sala Lauree, Facolta di Scienze Politiche, Sociologia, Comunicazione, piazzale Aldo Moro 5

Session 3: Macroeconometrics

**Chair: Carolina Serpieri (Sapienza University of Rome)**

09:30-10:30 "Higher-Order Moment Inequality Restrictions for SVARs" Filippo Ferroni (Universita di Bologna) (joint with Philippe Andrade and Leonardo Melosi)

Discussant: Giuseppe Ragusa (Sapienza University of Rome)

10:30-11:30 "The Systematic Origins of Monetary Policy Shocks" Klodiana Istrefi (Banque de France) (joint with Lukas Hack and Matthias Meier)

Discussant: Giacomo Mangiante (Banca d'Italia)

11:30-12:30 Coffee break

12:30-13.30 **Keynote Lecture by Fabio Canova** "Does the transmission of monetary policy shocks change when inflation is high?" (joint with Fernando Perez Forero)

14:00-15:30 at "La Limonaia" (invitation only)