[MISSING_PAGE_EMPTY:1]

**June 7\({}^{\rm th}\):** Sala Lauree, Facolta di Scienze Politiche, Sociologia, Comunicazione, piazzale Aldo Moro 5

**Session 2: The heterogenous effect of the green transition**

**Chair: Salvatore Nistico (Sapienza University of Rome)**

9:00-9:45 "Climate Policies, Macroprudential Regulation, and the Welfare Cost of Business Cycles" **Barbara Annicchiarico (Roma Tre University)** Marco Carli (Tor Vergata University) Francesca Diluiso (Bank of England)

Discussant: Fabio Di Dio (Sapienza University)

9:45-10:30 "Macro Shocks and Inequality" Francesco Furlanetto (Norges Bank) (joint with Drago Bergholt and Lorenzo Mori)

Discussant: Elisa Guglielminetti (Banca d'Italia)

10:30-11:00 Coffee break

11:00-11:45 "Distributional Effects of the Green Transition" **Andrea Colciago (Dutch Central Bank and University of Bicocca)** (joint with Guido Ascari, Timo Haber, Stefan Wohrmuller)

Discussant: **Andrey Alexandrov (Universita di Roma Tor Vergata)**

12:00-13:30 Policy Panel: Andrea Brandolini (Bank of Italy), Corrado Pollastri (Parliamentary Budget Office),

**Ottavio Ricchi (Director of the Economic and Financial Analysis and Research of the Treasury)**

13:30-15:00 Buffet Lunch 


